language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel # build images
  - docker tag udagram-api-feed dizolivemint/udagram-api-feed:v1 # tagging
  - docker tag udagram-api-feed dizolivemint/udagram-api-user:v1
  - docker tag udagram-api-feed dizolivemint/udagram-frontend:v1
  - docker tag udagram-api-feed dizolivemint/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dizolivemint/udagram-api-feed:v1
  - docker push dizolivemint/udagram-api-user:v1
  - docker push dizolivemint/udagram-frontend:v1
  - docker push dizolivemint/reverseproxy:v1

# safelist
branches:
  only:
  - main
  - staging